### ISSUE TITLE
Using attriube fullName for nickname?

### ISSUE THREAD

**Issue by Paule2020** [matrix-org/matrix-synapse-ldap3#102]
Hello,
is it possible to use attributs in LDAP for the nickname in matrix-synapse, e.g. fullname = nickname. Right now the nickname is cn.

Thanks
Paule2020

**Comment by richvdh** [comment]
yes it is. change the `attributes` settings

**Comment by Paule2020** [comment]
Hi,
well I tried...e.g. I chanced mail: "mail" and name: "fullName" as shown on my LDAP-Server, but still no chance...
