### ISSUE TITLE
is it possible to have multiple ldap servers with the same hostname.

### ISSUE THREAD

**Issue by f1-outsourcing** [matrix-org/matrix-synapse-ldap3#107]
Say I have 192.168.0.5, 192.168.0.6 and 192.168.0.7 configured with the hostname ldap.example.com. 

Does synapse then choose a random ip, and when that ldap server fails, will it automatically use the next one?

**Comment by richvdh** [comment]
As far as I am aware an IP is chosen by the C library, and there will be no failover.

I'm afraid this is not a support forum; please use it for reporting bugs rather than asking questions.
