### ISSUE TITLE
Version of this module included in the deb packages seems to be outdated (multiple ldap server support)

### ISSUE THREAD

**Issue by sim0nx** [matrix-org/matrix-synapse-ldap3#111]
**Describe the bug**
The issue described in #11 has been fixed by #85 though the version included in the deb packages does not seem to include this fix.

**To Reproduce**
Using the sample config, include multiple ldap servers as a list.

**Expected behavior**
Should just accept the config list and work :-)

**Additional context**
It still throws an error when a user tries to authenticate. Workaround is to specify multiple ldap server blocks, instead of specifying a list of servers in the **uri** variable.

**Comment by richvdh** [comment]
I've now released v0.1.5. The next release of the synapse debs should therefore include these changes.
