### ISSUE TITLE
ldaps:// doesn't work

### ISSUE THREAD

**Issue by 4nd3r** [matrix-org/matrix-synapse-ldap3#12]
from #10

with ``uri: "ldaps://ldap.example.com"`` connection still goes to port 389 (not port 636 as ldaps should).

**Comment by mweinelt** [comment]
Do you have the logs that show that behaviour? URI Scheme handling happens within the ldap3 library and I'm using it like this without issues.

**Comment by 4nd3r** [comment]
I can see that with tcpdump in LDAP server.

login itself is succesful, of course. but it's all unencrypted :>

**Comment by 4nd3r** [comment]
tcpflow:
```
# tcpflow host x.x.x.x
tcpflow: listening on eth0
^Ctcpflow: terminating
# cat x.x.x.x.36648-y.y.y.y.00389
0G      `B/uid=testuser,ou=foo,ou=bar,dc=example,dc=com
                                                          ThePassword
```

**Comment by mweinelt** [comment]
If the scheme is `ldaps` it sets the connection parameters for SSL/TLS.
https://github.com/cannatag/ldap3/blob/master/ldap3/utils/uri.py#L91

If no port was specified and SSL/TLS was enabled, set port to 636
https://github.com/cannatag/ldap3/blob/master/ldap3/utils/uri.py#L93-L95

The port should be set starting with `ldap3>=1.2.1`. What version are you currently running with?

You can set the port manually if your version is older than that.
`uri: "ldaps://ldap.example.com:636"`

**Comment by 4nd3r** [comment]
setting port didn't help.

but after i upgraded python-ldap3 to jessie-backports version (0.9.9.3, was 0.9.4.2), ``ldaps://`` works and connects to correct port even if you don't specify it.

there should be somewhere sticky notice about that.

thanks!

**Comment by 4nd3r** [comment]
so, basically, my issue wasn't related to this external module at all...?

**Comment by mweinelt** [comment]
Yup, it's just the varying deployments of the ldap3 library.
