### ISSUE TITLE
ldaps + start_tls

### ISSUE THREAD

**Issue by fooness** [matrix-org/matrix-synapse-ldap3#121]
_This a question, not a feature request … though this maybe could be improved upon documentation-wise in the README._

When using `ldaps://example.com`, do you have to set `start_tls: false`, does the setting `start_tls: $value` not matter, or does `start_tls: true` even interfere when it’s set to `true` in combination with `ldaps://` and maybe even port `636`?

Thank you very much!

**Comment by erikjohnston** [comment]
Looking at the source of `ldap3` library it looks like it will ignore our attempts to use `start_tls` if the connection is already TLS, but it's probably safer to just set it to `start_tls: false` (which is the default)
