### ISSUE TITLE
Add option to specify ca certificate or disable ca certificate validation

### ISSUE THREAD

**Issue by uumas** [matrix-org/matrix-synapse-ldap3#122]
In the latest version ca certificate verification was enabled, which breaks ldap authentication when using self-signed certificates. The solution is to add a config option to specify own ca certificate for ldap. It would also be nice to be able to disable certificate verification altogether.

**Comment by pwFoo** [comment]
I have a internal ldap server with self signed certificate and my login is broken. Any fix to ignore tls verification for self signed ldap certificate?

**Comment by reivilibre** [comment]
Fixed by #136 (coming soon).
