### ISSUE TITLE
Using SSL instead of start TLS?

### ISSUE THREAD

**Issue by Paule2020** [matrix-org/matrix-synapse-ldap3#132]
Hi,
is it possible to use SSL instead of start TLS?
I'm asking because I use a reverse proxy to connect to my ldap-server and the reverse proxy is listening on https port 443.
When I try to connect using start TLS it is not possible to establish an connection.
I didn't manage to set up an start TLS reverse proxy.

Any ideas?

**Comment by erikjohnston** [comment]
I think you can simply use a `ldaps://` url without setting `start_tls` option. 

Please reopen if that doesn't work.
