### ISSUE TITLE
Readme mentions non-existent "mode" config setting

### ISSUE THREAD

**Issue by babolivier** [matrix-org/matrix-synapse-ldap3#158]
The 3rd example in the "Usage" section (https://github.com/matrix-org/matrix-synapse-ldap3#usage) includes a config line that says `mode: "search"`, even though the module has never had such a setting. The mode to use is determined by whether `bind_dn` exists at the top level of the configuration ("search" if it's there, "simple" otherwise).

**Comment by richvdh** [comment]
dup #125
