### ISSUE TITLE
Account creation fails for users with no email

### ISSUE THREAD

**Issue by kyrias** [matrix-org/matrix-synapse-ldap3#16]
>when letting ldap auth create a user, if the user doens't have an email attribute it results in a rather generic "Missing JSON keys" error.
>
>to fix I edited synapse/handlers/auth.py and changed mail = attrs[self.ldap_attributes['mail']][0] to
>
>     try:
>         mail = attrs[self.ldap_attributes['mail']][0]
>     except KeyError:
>         mail = ""
>         pass

— @chrwei, matrix-org/synapse#1135

**Comment by mweinelt** [comment]
Resolved in 98ce626871ba2add8b100044e52eb7d5f0b829dd

**Comment by maxidor** [comment]
Maybe this should be included in a release? people keep having this problem (various users in Matrix rooms) and just lately with #36 simply because it's not available in the repos.
