### ISSUE TITLE
Ubuntu 20.04 error AttributeError

### ISSUE THREAD

**Issue by xfn2020** [matrix-org/matrix-synapse-ldap3#160]
matrix-synapse-ldap3 installed from repo give an error:

matrix-synapse[30831]: Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
:     exec(code, run_globals)
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 440, in <modul>
:     main()
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 430, in main
:     hs = setup(sys.argv[1:])
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/app/homeserver.py", line 323, in setup
:     config = HomeServerConfig.load_or_generate_config(
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 697, in load_or_>
:     obj.parse_config_dict(
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 721, in parse_co>
:     self.invoke_all(
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/_base.py", line 347, in invoke_a>
:     res[config_class.section] = getattr(config, func_name)(*args, **kwargs)
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/config/modules.py", line 32, in read_co>
:     self.loaded_modules.append(load_module(module, config_path))
:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/synapse/util/module_loader.py", line 50, in loa>
:     provider_class = getattr(module, clz)

**AttributeError: module 'ldap_auth_provider' has no attribute 'LdapAuthProviderModule'**

what's wrong?

**Comment by reivilibre** [comment]
How are you installing Synapse and this module?
What'

**Comment by xfn2020** [comment]
Thanks for replying so quickly.

>>How are you installing Synapse and this module?

apt install matrix-synapse-ldap3 

**version:**
matrixsynapse version is 1.11.0-1
matrix-synapse-ldap3  version is 0.1.3-4

part of homeserver.yaml:

modules:
 - module: "ldap_auth_provider.LdapAuthProviderModule"
   config:
     enable: true
     mode: "search"
     uri: "ldap://10.16.10.1:389"
     start_tls: true
     base: "OU=_GK,DC=organisation,DC=com"
     attributes:
        uid: "cn"
        mail: "mail"
        name: "sAMMAccountName"
     bind_dn: "CN=adm.ldap,OU=Service,DC=organisation,DC=com"
     bind_password: "qqqqqq"

**Comment by xfn2020** [comment]
Any thoughts?

**Comment by DMRobertson** [comment]
> apt install matrix-synapse-ldap3
>
> **version:**
> matrixsynapse version is 1.11.0-1
> matrix-synapse-ldap3 version is 0.1.3-4

These are old versions, I'm guessing [from the official ubuntu repositories](https://packages.ubuntu.com/search?keywords=matrix-synapse&searchon=names&suite=all&section=all). Please be aware that
- this version of Synapse [has known security vulnerabilities](https://github.com/matrix-org/synapse/security/advisories?state=published)
- the [matrix.org debian packages](https://matrix-org.github.io/synapse/latest/setup/installation.html#debianubuntu) for synapse come with the ldap3 plugin enabled.

I think the configuration listed in this repository's README only applies to the most recent release of matrix-synapse-ldap3. If you do want to use version 0.1.3-4 you'll need to look at the 0.1.3 version of the README: see https://github.com/matrix-org/matrix-synapse-ldap3/tree/v0.1.3#usage.

**Comment by richvdh** [comment]
yup, if you're going to use ubuntu's ancient packages, please file bugs with them, not us.

**Comment by xfn2020** [comment]
According this:
https://matrix-org.github.io/synapse/latest/setup/installation.html#debianubuntu

"To install the latest release:

sudo apt install -y lsb-release wget apt-transport-https
sudo wget -O /usr/share/keyrings/matrix-org-archive-keyring.gpg https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/matrix-org-archive-keyring.gpg] https://packages.matrix.org/debian/ $(lsb_release -cs) main" |
    sudo tee /etc/apt/sources.list.d/matrix-org.list
sudo apt update
sudo apt install matrix-synapse-py3"

I'v got anyway the same version  - 1.11.0-1

**Comment by DMRobertson** [comment]
The matrix.org package for Synapse comes with ldap3 plugin included. You should `apt remove matrix-synapse-ldap3`.

**Comment by xfn2020** [comment]
Hmm, it's work now. I do not change config file.

BTW, "apt remove matrix-synapse-ldap3" doesn't affect.

Now close to the solution, but still have error:

2022-03-24 14:47:37,501 - synapse.rest.client.login - 278 - INFO - POST-38 - Got login request with identifier: {'type': 'm.id.user', 'user': 'ldap_user_login'}, medium: None, address: None, user: None
2022-03-24 14:47:37,516 - ldap_auth_provider - 541 - WARNING - sentinel - Error during LDAP authentication: wrap socket error: [Errno 104] Connection reset by peer
2022-03-24 14:47:37,516 - ldap_auth_provider - 646 - WARNING - sentinel - Error during LDAP authentication: wrap socket error: [Errno 104] Connection reset by peer
2022-03-24 14:47:37,516 - ldap_auth_provider - 233 - WARNING - sentinel - Error during ldap authentication: wrap socket error: [Errno 104] Connection reset by peer
2022-03-24 14:47:37,516 - synapse.storage.database - 739 - WARNING - sentinel - Starting db txn 'get_users_by_id_case_insensitive' from sentinel context
2022-03-24 14:47:37,516 - synapse.storage.database - 790 - WARNING - sentinel - Starting db connection from sentinel context: metrics will be lost

**Comment by xfn2020** [comment]
Disabled tls:

start_tls: false

and succefully logined.

It's ok now, guys. Thanks for help.
