### ISSUE TITLE
Installation / Getting started guide

### ISSUE THREAD

**Issue by maxidor** [matrix-org/matrix-synapse-ldap3#17]
Is there an installation and/or Getting Started guide somewhere on how to use this plugin for those that are not familiar with python and have no clue how to make this work?

**Comment by mweinelt** [comment]
It depends a bit on how you installed your synapse.

There is a debian package available, called `python-matrix-synapse-ldap3` in the matrix debian package repository.

You can also install it through pythons package manager pip: `pip install matrix-synapse-ldap3`

Then add the configuration block, which is shown on the README to your homeserver.yaml, adapt it and restart.

**Comment by maxidor** [comment]
Great, I used the debian package for synapse and use the one for this - works flawlessly.
I've created PR #18 to make those obvious.
