### ISSUE TITLE
Debugging an `invalidCredentials` from AD

### ISSUE THREAD

**Issue by edwardando** [matrix-org/matrix-synapse-ldap3#182]
Dear all,
I'm coming from [spantaleev/matrix-docker-ansible-deploy ](spantaleev/matrix-docker-ansible-deploy) trying to debug a weird issue.
I'm currently testing a login with an email address, the AD/LDAP search looks like it works correctly because (sometimes...) it comes up with the right DN, but fails to authenticate with a `invalidCredentials`.

If I take the same looked up DN and do (on the same machine):
`ldapwhoami -vvv -H ldaps://ldap.epfl.ch -D 'cn=Edward Carlo Giorgio Ando,ou=xxx,ou=yyy,ou=zzz,o=aaa,c=bb' -x -W`
I give my password and I can log in fine... where do I go from here?

**Comment by edwardando** [comment]
Actually it looks like the auth works, but then causes:

`synapse.handlers.auth - 2227 - WARNING - sentinel - Failed to run module API callback <function load_single_legacy_password_auth_provider.<locals>.async_wrapper.<locals>.wrapped_check_3pid_auth at 0x7f697568d300>: 'NoneType' object has no attribute 'startswith'`

**Comment by clokep** [comment]
The only call to `startswith(...)` is at:

https://github.com/matrix-org/matrix-synapse-ldap3/blob/2584736204165f16c176567183f9c350ee253f74/ldap_auth_provider.py#L117-L119

It seems like that's getting called w/ a `None` `username` for some reason. I'm having trouble tracking down how that could be possible though?

**Comment by edwardando** [comment]
Thanks for the reply, that's a good start, let me dig a bit...

**Comment by DMRobertson** [comment]
@edwardando did your investigations dig up any clues? (I'm just checking on a few stale issues.)

**Comment by edwardando** [comment]
The problem magically went away, this is definitely stale, sorry, I'll close it.

**Comment by DMRobertson** [comment]
No worries. Thanks for confirming!
