### ISSUE TITLE
Active Directory login fault

### ISSUE THREAD

**Issue by slipeer** [matrix-org/matrix-synapse-ldap3#24]
**Description of problem**: login fault when try to auth with Active Directory and _user search base configured to domain/forest root_. 

**Error text in log**:

> INFO - POST-3- LDAP search returned too many (4) results for 'username'

**Error reason**: dirty _conn.response_ lenght check. There not only 'searchResEntry' type entries may present in LDAP responce. There may be 'searchResRef' type entries (most often occur in MS AD, **but can also be found in other LDAP servers**). In Active Directory forest root there always 3 refferal links, so in LDAP response, 4 objects are obtained: one user object with type 'searchResEntry' and tree 'searchResRef' objects.

**Solution**: count in _conn.response_  only 'searchResEntry' type entries, and (in the ideal case) correctly handle LDAP referral links.

**Comment by mweinelt** [comment]
Would you think of this pull request as a good solution to this issue? https://github.com/matrix-org/matrix-synapse-ldap3/pull/8

**Comment by slipeer** [comment]
Yes. It partialy (without proper LDAP referral hendling) fix problem.

**Comment by Jazun713** [comment]
Curious if there's any update on this?  I'm seeing this issue as well.

**Comment by mweinelt** [comment]
@slipeer adresses this in #26
