### ISSUE TITLE
Umlaut in AD Useraccount =  failed: invalidCredentials

### ISSUE THREAD

**Issue by Kleingeldprinz** [matrix-org/matrix-synapse-ldap3#30]
When a user has an umlaut in the cn Part, the login fails.

Binding against LDAP failed for 'CN=Max KrÃ¤he,OU=LAB,OU=Benutzer,DC=domain,DC=de' failed: invalidCredentials

**Comment by maxidor** [comment]
That character is not within the character set allowed for Matrix IDs.

See the [spec](http://matrix.org/docs/spec/intro.html#user-identifiers) for more details.

**Comment by Kleingeldprinz** [comment]
Ok sorry for beeing so short-worded.
Let me clarify:

My config:

     attributes:
        uid: "sAMAccountName"
        mail: "mail"
        name: "sAMAccountName"

(At this point, thanks again for the mail thingy !)

The SAM Name is: mkraehe
This is the riot login name. So the Matrix ID has to be "mkraehe" ? There is an umlaut in the cn, but the cn is not used for the matrix id (just internal for the ldap3 plugin?).

**Comment by maxidor** [comment]
The LDAP plugin needs the `dn` to validate the password (that's the only way to actually try a login on LDAP), and for that you use filters. In that config, it would do a search with `sAMAccountName` having a value with the provided login.
If any user match that filter, it will then use the `dn`.

so `uid` config item what you want to use as the username. `dn` will never be a good value for sure.
`sAMAccountName` or `userPrincipalName` (depends on the LDAP setup) usually contain the expected username.

**Comment by Kleingeldprinz** [comment]
@maxidor Thank you for clarify this.
So, there is no way to use umlaute in Active directory, even when they are not in the uid identifier? (Like sAMAccountName).
I think this is a bug. It seems like an encoding error. 
There is no umlaut in
- the UID of Matrix
- the identifier in the AD (sAMAccountName)

Only in the  dn. (The whole string).

I'm using an Windows Server 2008R2 AD.

**Comment by richvdh** [comment]
duplicate #33 / #72
