### ISSUE TITLE
Fill Email in user profile from LDAP mail field on user creation

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix-synapse-ldap3#34]
Auth work successfull via LDAP, but in user profiles Email field are empty (even if I fill correct "mail" account at `ldap_auth_provider.LdapAuthProvider` config. 

So I must manually fill it and complete email verification process with activation link for each LDAP user.

Will be good to auto-fill email field from LDAP mail field info.

**Comment by andersruneson** [comment]
Isn't this already described in #23? If so maybe this can be closed?

**Comment by MurzNN** [comment]
Yes, #23 topic is about display name, but comments also for email field, so leave this as duplicate of #23.
