### ISSUE TITLE
TLS certificates are not validated

### ISSUE THREAD

**Issue by Criena** [matrix-org/matrix-synapse-ldap3#44]
With ldap3 this can be done rather easy:

```
import ssl

tls = ldap3.Tls(validate=ssl.CERT_REQUIRED)
server = ldap3.Server(self.ldap_uri, get_info=None, tls=tls)
```

Ideally this should be made optional via the config (possibly with providing a CA file opposed to using the system's cert store).

**Comment by UweSauter** [comment]
This should also allow the configuration of its own cerfificate, key and CA file.

See [ldap3 doumentation](https://ldap3.readthedocs.io/en/latest/ssltls.html)

**Comment by richvdh** [comment]
:scream:

**Comment by Criena** [comment]
Created a PR for this: #89

**Comment by Criena** [comment]
PR #89 has been merged.
