### ISSUE TITLE
Users from different Organizational Units can't login

### ISSUE THREAD

**Issue by Geeman9** [matrix-org/matrix-synapse-ldap3#47]
I can't find a solution for this problem.
If I set ` base: "ou=Alytus,dc=KP,dc=local"` users from this OU login without any problems. But users from other OU can't login because LDAP don't find such user.
If I set ` base: "dc=KP,dc=local"` non of user can login because LDAP gets error
`ldap_auth_provider - 397 - INFO - POST-4- LDAP search returned too many (4) results for 'lina.gaubiene'`
And for all users I get 4 results. Using filter I can filter good result, but I can't find how to filter those 3 bad results.

**Comment by Geeman9** [comment]
Please help!

> base: "dc=KP,dc=local"

No matter what query I send to Active Directory (Windows Server 2016) I always get minimum 3 results.

**Comment by mweinelt** [comment]
Maybe by their objectClass?

**Comment by ariesbeck** [comment]
We are currently experiencing the exact same situation. Did you ever find a fix?

**Comment by Geeman9** [comment]
Yes, ldap3 do not work. You must use mxisd https://github.com/kamax-io/mxisd
