### ISSUE TITLE
Migrate existing users

### ISSUE THREAD

**Issue by Perflyst** [matrix-org/matrix-synapse-ldap3#67]
Is there a way to migrate existing users to a LDAP directory?
It seems like the internal database password table is looked up before LDAP is checked.

Is there a way to delete just the password (not the account) so that LDAP password is used instead or disable the internal password provider?

**Comment by helmut72** [comment]
Maybe this works also for you:
https://github.com/matrix-org/synapse/issues/1707#issuecomment-405455882

**Comment by richvdh** [comment]
synapse has an option to disable the local user database.
