### ISSUE TITLE
Can't log in with LDAP

### ISSUE THREAD

**Issue by pebou** [matrix-org/matrix-synapse-ldap3#69]
Hi,

I've installed Synapse on a Debian Stretch from the deb repo. It is linked to Nginx as reverse proxy.
I've setup my LDAP server in `homeserver.yaml` and put the log on DEBUG

Here are the log i have when i try to log in as a ldap user:
```
ldap_auth_provider - 91 - DEBUG - POST-1- Attempting LDAP connection with ldaps://XXXXX:XXX
ldap_auth_provider - 342 - DEBUG - - Established LDAP connection in search mode: ldaps://XXXXXX:XXX - ssl - user: cn=XXX,dc=XXX,dc=XXX - not lazy - unbound - closed - <no socket> - tls not started - not listening - SyncStrategy - internal decoder
```

I can't log in. Any ideas ?
If you need more details let me know 🙂 

Thank you !

**Comment by nnagibator228** [comment]
Hello, how did you managed to fix that issue? I'm facing it right now.
