### ISSUE TITLE
Authentication never makes it to try LDAP

### ISSUE THREAD

**Issue by cmchittom** [matrix-org/matrix-synapse-ldap3#70]
I've configured my Synapse server (version 1.2.1) as in the README to allow LDAP. However, any attempt to authenticate just immediately fails, and no LDAP events ever show up in homeserver.log, even with logging set to DEBUG. I've tried setting localdb_enabled to false, but there was no change in behavior.  Can anyone point me in the right direction to figure this out, or at least get more information?

**Comment by richvdh** [comment]
#synapse:matrix.org for support.
