### ISSUE TITLE
Bump version on pypi

### ISSUE THREAD

**Issue by jcgruenhage** [matrix-org/matrix-synapse-ldap3#75]
This has seen a bunch of development over the last two years, but most people don't benefit from that because there's not been a release. Please tag this as 0.2.0 or something and upload it to pypi.org

**Comment by richvdh** [comment]
looks like this happened; there was a 0.1.4 release in november.

**Comment by jcgruenhage** [comment]
Sorry, forgot to close this after it was fixed :/
