### ISSUE TITLE
Does this code work with python3 ?

### ISSUE THREAD

**Issue by epsilon-0** [matrix-org/matrix-synapse-ldap3#95]
I am trying to port the package for OpenBSD and was wondering if it is possible to get this to work with python 3, given that python 2 has reached EOL?

Thanks.

**Comment by clokep** [comment]
@epsilon-0 My understanding is that this code is already Python 3 compatible, are you having issues with it under Python 3?

**Comment by epsilon-0** [comment]
Not at all, I just wanted to get confirmation from here as on pypi it only mentions py2.

Thanks a lot for confirming.
