### ISSUE TITLE
Logging doent work?

### ISSUE THREAD

**Issue by Paule2020** [matrix-org/matrix-synapse-ldap3#97]
Hello,
my log.yaml lookes like this and DEBUG-Logging with LDAP_auth doesnt work.

```version: 1

formatters:
    precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

filters:
    context:
        (): synapse.logging.context.LoggingContextFilter
        request: ""

handlers:
    file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
        filename: /var/log/matrix-synapse/homeserver.log
        maxBytes: 104857600
        backupCount: 10
        filters: [context]
        encoding: utf8
        level: DEBUG

    console:
        class: logging.StreamHandler
        formatter: precise
        filters: [context]

loggers:
    ldap3:
     level: DEBUG
   ldap_auth_provider:
     level: DEBUG
    synapse.storage.SQL:
        # beware: increasing this to DEBUG will make synapse log sensitive
        # information such as access tokens.
        level: INFO



root:
    level: INFO
    handlers: [file, console]

disable_existing_loggers: false
```

error when tryining to start the server, sometimes the server runs for 1sec

Aug 08 12:41:45 Ubuntu-Element systemd[1]: Starting Synapse Matrix homeserver...
Aug 08 12:41:46 Ubuntu-Element systemd[1]: Started Synapse Matrix homeserver.
root@Ubuntu-Element:~# systemctl status  matrix-synapse
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2020-08-08 12:41:53 CEST; 1s ago
    Process: 8397 ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys (code=exited, status=0/SUCCESS)
   Main PID: 8412 (python)
      Tasks: 1 (limit: 2286)
     Memory: 68.9M
     CGroup: /system.slice/matrix-synapse.service
             └─8412 /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/

Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:   File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:     raise ParserError("while parsing a block mapping", self.marks[-1],
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: yaml.parser.ParserError: while parsing a block mapping
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:   in "<byte string>", line 8, column 1:
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:     version: 1
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:     ^
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: expected <block end>, but found '<block mapping start>'
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:   in "<byte string>", line 38, column 4:
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:        ldap_auth_provider:
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]:        ^
root@Ubuntu-Element:~# systemctl status  matrix-synapse
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: activating (start-pre) since Sat 2020-08-08 12:41:57 CEST; 3ms ago
Cntrl PID: 8422 (systemd)
      Tasks: 0 (limit: 2286)
     Memory: 0B
     CGroup: /system.slice/matrix-synapse.service
             └─8422 (python)

Aug 08 12:41:57 Ubuntu-Element systemd[1]: Starting Synapse Matrix homeserver...
root@Ubuntu-Element:~# systemctl status  matrix-synapse
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: activating (start-pre) since Sat 2020-08-08 12:42:03 CEST; 953ms ago
Cntrl PID: 8438 (python)
      Tasks: 1 (limit: 2286)
     Memory: 56.8M
     CGroup: /system.slice/matrix-synapse.service
             └─8438 /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys

Aug 08 12:42:03 Ubuntu-Element systemd[1]: Starting Synapse Matrix homeserver...
root@Ubuntu-Element:~# systemctl status  matrix-synapse
● matrix-synapse.service - Synapse Matrix homeserver
     Loaded: loaded (/lib/systemd/system/matrix-synapse.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sat 2020-08-08 12:42:06 CEST; 1s ago
    Process: 8438 ExecStartPre=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ --generate-keys (code=exited, status=0/SUCCESS)
    Process: 8446 ExecStart=/opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path=/etc/matrix-synapse/homeserver.yaml --config-path=/etc/matrix-synapse/conf.d/ (code=exited, status=1/FAILURE)
   Main PID: 8446 (code=exited, status=1/FAILURE)

Aug 08 12:42:06 Ubuntu-Element systemd[1]: matrix-synapse.service: Main process exited, code=exited, status=1/FAILURE
Aug 08 12:42:06 Ubuntu-Element systemd[1]: matrix-synapse.service: Failed with result 'exit-code'.

**Comment by clokep** [comment]
@Paule2020 Could you please edit your description to use some code blocks (with three ticks) -- the indentation is important for those files and isn't readable in the current format.

**Comment by clokep** [comment]
In general, any support questions are best directed to #synapse:matrix.org though.

**Comment by Paule2020** [comment]
thanks for the info I must use three ticks...

**Comment by clokep** [comment]
It looks like Synapse is failing to start up though, seems there's a config error:

```
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: File "/opt/venvs/matrix-synapse/lib/python3.8/site-packages/yaml/parser.py", line 438, in parse_block_mapping_key
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: raise ParserError("while parsing a block mapping", self.marks[-1],
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: yaml.parser.ParserError: while parsing a block mapping
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: in "", line 8, column 1:
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: version: 1
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: ^
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: expected , but found ''
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: in "", line 38, column 4:
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: ldap_auth_provider:
Aug 08 12:41:54 Ubuntu-Element matrix-synapse[8412]: ^
```

**Comment by Paule2020** [comment]
I thing the problem where 3 missing spaces, each one for  ldap_auth_provider and the three following lines....
